version: "3"
services:
  airsoftteams:
    build: .
    container_name: "airsoftteams"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=q1w2e3r4
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=airsoftteams
      - POSTGRES_HOST=postgresql
      - WAIT_HOSTS=postgresql:5432
    #    command: bash -c "npm run db-migrate-up && npm run db-seeders-up && node app.js"
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    links:
      - postgresql
  postgresql:
    container_name: "postgresql"
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_DB: airsoftteams
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: q1w2e3r4
    ports:
      - "5432:5432"